### ISSUE TITLE
Taking 30-40 seconds for image size 500KB

### ISSUE THREAD

**Issue by sanjaycedti** [Raincal/blurhash#11]
It takes around 30-40 seconds to generate blur hash if image size is 500KB or bigger. Here is the code

```
static Future<String> encode(Uint8List bytes) async {
  final blurHash = await BlurHash.encode(bytes, 3, 4);
  return blurHash;
}
```

**Comment by sanjaycedti** [comment]
I also tried to spawn a new thread to deal with the UI freezing but got this error -

```
static Future<String> encode(Uint8List bytes) async {
    final startTime = Helper.timestamp();
    
    final receivePort = new ReceivePort();
    await Isolate.spawn(_encode, _EncodeParams(bytes, receivePort.sendPort));
    final String blurHash = await receivePort.first;

    print('BlurHashHelper encoding took ${ Helper.timestamp() - startTime } ms');
    return blurHash;
  }

  static void _encode(_EncodeParams params) async {
    final blurHash = await BlurHash.encode(params.bytes, 3, 4);
    // BlurHash.encode(blurHash, width, height)
    params.sendPort.send(blurHash);
  }

class _EncodeParams {
  final Uint8List bytes;
  final SendPort sendPort;

  _EncodeParams(this.bytes, this.sendPort);
}
```


Error:
`Exception has occurred.
FlutterError (ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before 'runApp()' has been called (for example, during plugin initialization), then you need to explicitly call the 'WidgetsFlutterBinding.ensureInitialized()' first.
If you're running a test, you can call the 'TestWidgetsFlutterBinding.ensureInitialized()' as the first line in your test's 'main()' method to initialize the binding.)`

**Comment by Raincal** [comment]
You should scale your images down before encoding.

**Comment by hiashutoshsingh** [comment]
it's still taking too much time anyone resolved this?

what do exactly `scaling images` is?

**Comment by claytonjacobs** [comment]
> it's still taking too much time anyone resolved this?
> 
> what do exactly `scaling images` means? @Raincal

@hiashutoshsingh 
You can use [image](https://pub.dev/packages/image) to "scale your images down". Original [Blurhash documentation](https://github.com/woltapp/blurhash) actually recommends you encode a thumbnail of your image instead of the full-resolution image -- `"If you are creating thumbnails, run BlurHash on those instead of the full images."`

**Comment by MzeeAlii** [comment]
Wow! And I've spent 4 hours trying each different way to achieve parallelism only to get discover this.

Okay, let's spawn an isolate to scale down the image and encode the blur of the scaled-down image on a main thread.

And see how it goes.
