### ISSUE TITLE
0.3.0 release?

### ISSUE THREAD

**Issue by lyio** [Raincal/blurhash#15]
Will there be a proper 0.3.0 release anytime soon? We have been using the pre-release version for quite some time now and I was wondering when the `-nullsafey.1` will be dropped.

**Comment by hiashutoshsingh** [comment]
Hey @Raincal, where is the new release?

**Comment by hiashutoshsingh** [comment]
my bad it was in null safety version:
https://pub.dev/packages/blurhash/versions/0.3.0-nullsafety.0/

@lyio you can use this one
