### ISSUE TITLE
iOS build fail : pngData() has been renamed to 'UIImagePNGRepresentation(_:)'

### ISSUE THREAD

**Issue by dfdgsdfg** [Raincal/blurhash#3]
iOS build failed. Android is just okay.

> 'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'

/Users/user/flutter/.pub-cache/hosted/pub.dartlang.org/blurhash-0.1.3/ios/Classes/SwiftBlurhashPlugin.swift:21:27: 'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'

**Comment by Raincal** [comment]
You need to upgrade Swift version to 5.
<img width="1134" alt="屏幕快照 2020-03-18 07 16 16 PM" src="https://user-images.githubusercontent.com/6279478/76955480-3f159a00-694d-11ea-8ab9-130a15b37fd4.png">
