### ISSUE TITLE
Any chance of an "encode" option

### ISSUE THREAD

**Issue by andrewpmoore** [Raincal/blurhash#4]
Love the idea of this library, an encode would be great to send up with uploaded images (well at least for me as my backend servers are pretty dumb!)

**Comment by AirborneEagle** [comment]
I have not used it yet, but [this](https://pub.dev/packages/blurhash_dart) lib has encoding.

**Comment by Raincal** [comment]
This project uses the official implementation from [woltapp/blurhash](https://github.com/woltapp/blurhash). They didn't provide the kotlin implementation for encoding.
