### ISSUE TITLE
Example use causes Poor performance

### ISSUE THREAD

**Issue by AirborneEagle** [Raincal/blurhash#6]
when using this package for the first time, I structured my widget after the example included.
```
  @override
  void initState() {
    super.initState();
//    blurHashDecode();
  }

  Future<void> blurHashDecode() async {
    Uint8List imageDataBytes;
    try {
      // Decodes a BlurHash string to bytes
      imageDataBytes = await BlurHash.decode("LGKB2RMzk?yY-;w|~pIoOunOM_jD", 256, 256);
    } on PlatformException catch (e) {
      print(e.message);
    }

    if (!mounted) return;

    setState(() {
      _imageDataBytes = imageDataBytes;
    });
  }
```

But if I use this widget in a scrolling list, it will lock up the app for a few seconds when I try to scroll. I found that this is caused by the decoding being done in the init state.  I can comment out that single line, (`blurHashDecode();`)and it is just fine.

I think I will need to do the decoding elsewhere in my app. perhaps in the constructor of the data object, and then store the decoded bytes in a field of the data object itself.

Are there any suggestions, that may imrove performance here?

**Comment by Raincal** [comment]
Did you try the example app? You should decode blurHash in children widgets.

**Comment by AirborneEagle** [comment]
The title of the ticket mentions the example, because that is where I got the code from. 
You mean, did I run the example app? I did not. I  Copied and pasted the widget though. and without making any changes, it was causing the issue mentioned above.
When you say children widgets, do you mean, in a listView, that the decode should be done in the listTile?

**Comment by SwissCheese5** [comment]
I can attest to this. The dart inspector revealed that blurhash decoding takes a substantial chunk of performance. My use case is also inside a scrolling list.

When you scroll, items outside the view of the screen are destroyed and created as they move in and out of view. This causes blurhash decoding to happen constantly.

One way to resolve this is to cache the resulting Uint8List in temporary storage and just pull that. But I find that that's more of a shoddy workaround. Regardless, decoding is taking up a good chunk of my performance.

I'm going to try to move the decoding to a compute function and see if that works at all.
