### ISSUE TITLE
Why isn't this package pure dart

### ISSUE THREAD

**Issue by KalilDev** [Raincal/blurhash#9]
The computation shouldn't be much slower in pure dart, but it results in web, desktop and mobile support, an single codebase instead of the binding and the native implementations.

**Comment by Raincal** [comment]
I wrote this package in order to learn https://flutter.dev/docs/development/platform-integration/platform-channels.

> The computation shouldn't be much slower in pure dart, but it results in web, desktop and mobile support, an single codebase instead of the binding and the native implementations.

I agree with you. Currently, there are other pure dart implementations on GitHub. You can take a look.
